version: '3'
services:
  exp_db:
    container_name: exp_db
    build: ./config/database
    environment:    
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - expenses-network

  exp_api:
    container_name: exp_api
    build: ./api
    command: python main.py

    environment:
      - DATABASE_URL=mysql://root:password@exp_db:3306/mydb

    depends_on:
      - exp_db
    ports:
      - "8050:5000"
    networks:
      - expenses-network

volumes:
  db-data:

networks:  
  expenses-network:
